version: 2
jobs:
  build:
    working_directory: ~/erc721x
    docker:
      - image: circleci/node:8.15.1
    steps:
      - checkout
      - run:
            name: Authenticate with registry
            command: curl -u $ARTIFACTORY_PUBLISHING_USER:$ARTIFACTORY_PUBLISHING_PASSWORD https://pillarproject.jfrog.io/pillarproject/api/npm/auth >> ~/erc721x/.npmrc
      - run:
            name: set Registry
            command: npm config set registry https://pillarproject.jfrog.io/pillarproject/api/npm/npm/
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      # - run:
      #     name: build the 'dist' folder
      #     command: npm run build-production
      # - run: ls -al
      # - persist_to_workspace:
      #     root: dist
      #     paths:
      #       - index.js

  test:
    working_directory: ~/erc721x
    docker:
      - image: circleci/node:8.15.1
    steps:
      - checkout
      - run:
            name: Authenticate with registry
            command: curl -u $ARTIFACTORY_PUBLISHING_USER:$ARTIFACTORY_PUBLISHING_PASSWORD https://pillarproject.jfrog.io/pillarproject/api/npm/auth >> ~/erc721x/.npmrc
      - run:
            name: set Registry
            command: npm config set registry https://pillarproject.jfrog.io/pillarproject/api/npm/npm/
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install
          command: npm install
      # - run:
      #     name: unit-test
      #     command:  npm run test:coverage
      # - run:
      #     name: plato
      #     command:  npm run plato
      - store_artifacts:
          path: ./reports/
          destination: reports

  publish:
    working_directory: ~/erc721x
    docker:
      - image: circleci/node:8.11.3
    steps:
      - checkout
      - attach_workspace:
          at: ~/erc721x/dist
      - run: ls -al
      - run:
          name: Append circleCI build number to version
          command: |
            git config user.email "devops@pillar.io"
            git config user.name "Issabot"
            npm version $(node -e "const currentVersion=require('./package.json').version; const firstTwoDots=currentVersion.substring(0, currentVersion.lastIndexOf('.')+1); console.log(firstTwoDots);")$CIRCLE_BUILD_NUM
      - run:
            name: Authenticate with registry
            command: curl -u $ARTIFACTORY_PUBLISHING_USER:$ARTIFACTORY_PUBLISHING_PASSWORD https://pillarproject.jfrog.io/pillarproject/api/npm/auth >> ~/erc721x/.npmrc
      - run:
          name: Publish Package to Artifactory
          command: npm publish   --registry https://pillarproject.jfrog.io/pillarproject/api/npm/npm/
      - run:
          name: Announce Publish
          command: |
            chmod +x .circleci/announcePublish.sh
            .circleci/announcePublish.sh "ERC721x" "$(node -e "console.log(require('./package.json').name)")@$(node -e "console.log(require('./package.json').version)")"

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build
      - test
      - publish:
          requires:
            - test
          filters:
            branches:
              only:
                  - master
